kind: pipeline
name: Dronerino2

steps:
- name: build
  image: ubuntu:bionic
  environment:
    USERNAME:
      from_secret: username
    GDRIVE-TOKEN:
      from_secret: gdrive-token
    GDRIVE:
      from_secret: gdrive
    PASSWORD:
      from_secret: password
  commands:
  - apt-get update
  - apt-get install -y megatools git repo
  - cd ~/
  - wget ${gdrive}
  - cp gdrive /usr/bin/gdrive
  - chmod +x /usr/bin/gdrive
  - wget ${gdrive-token}
  - mkdir ~/.gdrive/ -p
  - mv token_v2.json ~./gdrive/
  - echo "idiot" >> idiot.txt
  - gdrive upload idiot.txt
