kind: pipeline
name: Dronerino2

steps:
- name: build
  image: ubuntu:bionic
  environment:
    GDRIVETOKEN:
      from_secret: gdrive-token
    GDRIVE:
      from_secret: gdrive
  commands:
  - apt-get update
  - apt-get install -y git repo wget
  - chmod +x build.sh
  - ./build.sh
  
