kind: pipeline
name: Dronerino2

steps:
- name: build
  image: ubuntu:bionic
  environment:
    USERNAME:
      from_secret: username
    GDRIVETOKEN:
      from_secret: gdrivetoken
    GDRIVE:
      from_secret: gdrive
    PASSWORD:
      from_secret: password
  commands:
  - apt-get update
  - apt-get install -y git repo wget
  - cd ~/
  - wget ${GDRIVE}
  - mv bluedoge-gdrive gdrive
  - cp gdrive /usr/bin/gdrive
  - chmod +x /usr/bin/gdrive
  - wget ${GDRIVETOKEN}
  - mv bd-gdrive-token token_v2.json
  - mkdir ~/.gdrive/ -p
  - mv token_v2.json ~./gdrive/
  - echo "me" >> idiot.txt
  - gdrive upload idiot.txt
